INSERT INTO CART VALUES(1);
INSERT INTO CART VALUES(2);
INSERT INTO CART VALUES(3);
INSERT INTO CART VALUES(4);

INSERT INTO USER VALUES (1,'UJWAL',1);
INSERT INTO USER VALUES (2,'RADITZ',2);
INSERT INTO USER VALUES (3,'DUKE',3);


INSERT INTO PRODUCT VALUES (1,350,'LET US C');
INSERT INTO PRODUCT VALUES (2,650,'JAVA BLACK BOOK');
INSERT INTO PRODUCT VALUES (3,450,'HEAD FIRST ANGULAR');
INSERT INTO PRODUCT VALUES (4,1200,'SIGNATURE');
INSERT INTO PRODUCT VALUES (5,300,'GARFIELD');
INSERT INTO PRODUCT VALUES (6,100,'FRONTLINE');
INSERT INTO PRODUCT VALUES (7,500,'CHROMOX');

INSERT INTO BOOKS VALUES ('YASH K','ENGINEERING','SK PUBLISHERS',1);
INSERT INTO BOOKS VALUES ('K CORMEN','ENGINEERING','MIT PRESS',2);
INSERT INTO BOOKS VALUES ('S SKEINA','ENGINEERING','TECH PRESS',3);

INSERT INTO APPARALS VALUES ('LEVI''S','JEANS','SLIM-FIT',4);
INSERT INTO APPARALS  VALUES ('LEVI''S','T-SHIRTS','GRAPHICS',5);
INSERT INTO APPARALS  VALUES ('RUPA','INNER-WEAR','VEST',6);
INSERT INTO APPARALS  VALUES ('JOCKEY','INNER-WEAR','UNDIES',7);

INSERT INTO PRODUCT_CATALOG VALUES (1,1,1,1);
INSERT INTO PRODUCT_CATALOG VALUES (1,2,1,1);
INSERT INTO PRODUCT_CATALOG VALUES (1,3,1,1);
INSERT INTO PRODUCT_CATALOG VALUES (1,4,1,1);
INSERT INTO PRODUCT_CATALOG VALUES (3,5,1,1);
INSERT INTO PRODUCT_CATALOG VALUES (2,7,1,1);
INSERT INTO PRODUCT_CATALOG VALUES (2,6,2,2);